# New line before prompt
add_newline = true

[character]
# success_symbol = "[❯](bold green) "
# error_symbol = "[❯](bold red) "
# vicmd_symbol = "[❮](bold green) "
success_symbol = "[ ➜](bold green) "
error_symbol = "[ ➜](bold red) "

[directory]
format = "[ $path $read_only]($style)[](bg:bold black fg:cyan)"
style = "bg:cyan fg:bold black dimmed"
truncation_length = 3
truncation_symbol = "…/"
symbol = "☁️"

[git_branch]
format = "[$symbol$branch ]($style)[](bg:bold black fg:purple)"
style = "bg:purple fg:bold black dimmed"

[git_state]
format = "[$state( $progress_current/$progress_total)]($style)"
style = "red"

[git_status]
format = "[ $all_status$ahead_behind ]($style)"
style = "yellow"

[package]
format = "[$symbol$version ]($style)"
style = "bold 208"

[aws]
format = "[\\($symbol$profile($region)\\)]($style)"
style = "blue"

[cmd_duration]
format = "[ \\(took $duration\\)]($style)"
style = "red"

[time]
format = "[ $time ]($style)[](bg:bold black fg:green)"
style = "bg:green fg:bold black dimmed"
disabled = false

# Format of prompt
# format = "$all"
# format = """
# $directory\
# $git_branch\
# $git_commit\
# $git_status\
# $package\
# $aws\
# $cmd_duration\
# $time
# """
